import type { RoommateProfile } from '../types/matching';

// Avatar URLs from the stitch HTML files
const avatars = [
  'https://images.unsplash.com/photo-1502672260266-1c1f517403ce?w=800&auto=format&fit=crop',
  'https://images.unsplash.com/photo-1502672260266-1c1f517403ce?w=800&auto=format&fit=crop',
  'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&auto=format&fit=crop',
  'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=600&auto=format&fit=crop',
  'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=600&auto=format&fit=crop',
  'https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=600&auto=format&fit=crop',
  'https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=600&auto=format&fit=crop',
  'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=600&auto=format&fit=crop',
];

export const mockProfiles: RoommateProfile[] = [
  {
    id: '1',
    userId: '101',
    fullName: 'Minh Khang',
    age: 21,
    avatar: avatars[0],
    gender: 'male',
    university: 'Đại học Kinh tế TP.HCM',
    budgetMin: 2500000,
    budgetMax: 4000000,
    sleepTime: 'normal',
    wakeTime: 'early',
    cleanliness: 4,
    isSmoker: false,
    drinksAlcohol: false,
    hasPets: true,
    isIntrovert: true,
    okWithSmoker: false,
    okWithPets: true,
    bio: 'Mình là sinh viên năm 3 ngành Kinh tế, thích đọc sách và nuôi mèo. Đang tìm bạn ở ghép gọn gàng, sạch sẽ, thích yên tĩnh.',
    isVerified: true,
    isActive: true,
    compatibilityScore: 95,
    location: 'Quận 1, TP.HCM',
  },
  {
    id: '2',
    userId: '102',
    fullName: 'Anh Tuấn',
    age: 22,
    avatar: avatars[1],
    gender: 'male',
    university: 'Đại học Bách Khoa TP.HCM',
    budgetMin: 3000000,
    budgetMax: 5000000,
    sleepTime: 'late',
    wakeTime: 'normal',
    cleanliness: 5,
    isSmoker: false,
    drinksAlcohol: true,
    hasPets: false,
    isIntrovert: false,
    okWithSmoker: false,
    okWithPets: true,
    bio: 'Gamer và coder. Tìm bạn cùng phòng chill, không gây ồn ào ban đêm là ổn.',
    isVerified: true,
    isActive: true,
    compatibilityScore: 98,
    location: 'Quận 10, TP.HCM',
  },
  {
    id: '3',
    userId: '103',
    fullName: 'Thu Hà',
    age: 20,
    avatar: avatars[2],
    gender: 'female',
    university: 'Đại học Ngoại Thương',
    budgetMin: 2000000,
    budgetMax: 3500000,
    sleepTime: 'early',
    wakeTime: 'early',
    cleanliness: 5,
    isSmoker: false,
    drinksAlcohol: false,
    hasPets: false,
    isIntrovert: true,
    okWithSmoker: false,
    okWithPets: false,
    bio: 'Mình là sinh viên năm 2, thích nấu ăn tại nhà. Tìm bạn gọn gàng, yêu sạch sẽ.',
    isVerified: true,
    isActive: true,
    compatibilityScore: 94,
    location: 'Quận 3, TP.HCM',
  },
  {
    id: '4',
    userId: '104',
    fullName: 'Đức Minh',
    age: 23,
    avatar: avatars[3],
    gender: 'male',
    university: 'Đại học Sư Phạm TP.HCM',
    budgetMin: 1800000,
    budgetMax: 3000000,
    sleepTime: 'normal',
    wakeTime: 'early',
    cleanliness: 3,
    isSmoker: true,
    drinksAlcohol: true,
    hasPets: false,
    isIntrovert: false,
    okWithSmoker: true,
    okWithPets: true,
    bio: 'Mình là sinh viên năm cuối, đang thực tập. Ít ở nhà, cuối tuần hay đi chơi.',
    isVerified: false,
    isActive: true,
    compatibilityScore: 72,
    location: 'Thủ Đức, TP.HCM',
  },
  {
    id: '5',
    userId: '105',
    fullName: 'Ngọc Trâm',
    age: 21,
    avatar: avatars[4],
    gender: 'female',
    university: 'Đại học RMIT',
    budgetMin: 5000000,
    budgetMax: 8000000,
    sleepTime: 'late',
    wakeTime: 'late',
    cleanliness: 4,
    isSmoker: false,
    drinksAlcohol: true,
    hasPets: true,
    isIntrovert: false,
    okWithSmoker: false,
    okWithPets: true,
    bio: 'Fashionista, lover of cats and coffee. Looking for a chill roommate who respects personal space.',
    isVerified: true,
    isActive: true,
    compatibilityScore: 88,
    location: 'Quận 7, TP.HCM',
  },
  {
    id: '6',
    userId: '106',
    fullName: 'Hoàng Long',
    age: 24,
    avatar: avatars[5],
    gender: 'male',
    university: 'Đại học Khoa Học Tự Nhiên',
    budgetMin: 2000000,
    budgetMax: 3500000,
    sleepTime: 'very_late',
    wakeTime: 'late',
    cleanliness: 3,
    isSmoker: false,
    drinksAlcohol: false,
    hasPets: false,
    isIntrovert: true,
    okWithSmoker: true,
    okWithPets: false,
    bio: 'Nghiên cứu sinh ngành Vật lý, hay ngủ muộn vì lab. Cần không gian yên tĩnh.',
    isVerified: true,
    isActive: true,
    compatibilityScore: 81,
    location: 'Quận 5, TP.HCM',
  },
  {
    id: '7',
    userId: '107',
    fullName: 'Mai Linh',
    age: 19,
    avatar: avatars[6],
    gender: 'female',
    university: 'Đại học Kinh tế TP.HCM',
    budgetMin: 2500000,
    budgetMax: 4000000,
    sleepTime: 'early',
    wakeTime: 'early',
    cleanliness: 5,
    isSmoker: false,
    drinksAlcohol: false,
    hasPets: false,
    isIntrovert: false,
    okWithSmoker: false,
    okWithPets: true,
    bio: 'Năm nhất UEH, thích chạy bộ buổi sáng. Tìm bạn vui vẻ, hoạt bát!',
    isVerified: false,
    isActive: true,
    compatibilityScore: 91,
    location: 'Bình Thạnh, TP.HCM',
  },
  {
    id: '8',
    userId: '108',
    fullName: 'Quốc Bảo',
    age: 22,
    avatar: avatars[7],
    gender: 'male',
    university: 'Đại học FPT',
    budgetMin: 3000000,
    budgetMax: 5500000,
    sleepTime: 'late',
    wakeTime: 'normal',
    cleanliness: 4,
    isSmoker: false,
    drinksAlcohol: true,
    hasPets: true,
    isIntrovert: false,
    okWithSmoker: false,
    okWithPets: true,
    bio: 'Sinh viên IT yêu thú cưng. Có 1 chú golden nhỏ cực ngoan. Cần bạn không dị ứng lông.',
    isVerified: true,
    isActive: true,
    compatibilityScore: 85,
    location: 'Quận 9, TP.HCM',
  },
];

/** All universities available in mock data for filter dropdown */
export const mockUniversities = [
  ...new Set(mockProfiles.map((p) => p.university).filter(Boolean)),
] as string[];

/** All districts available in mock data for filter dropdown */
export const mockDistricts = [
].sort();
