"""
Mock data for AI Service development.
Mirrors the frontend mockData/ to ensure consistency.
"""

from app.models.listing import Listing, ListingTag, ListingFacility, ListingPolicy, ListingImage, ListingReview
from app.models.matching import RoommateProfile

# ── Mock Listings ────────────────────────────────────────────────────

MOCK_LISTINGS: list[dict] = [
    {
        "id": "1",
        "landlord_id": "ll_1",
        "title": "Sky Garden Loft - Cao cấp",
        "description": "Căn hộ loft siêu đẹp với view thành phố toàn cảnh. Thiết kế hiện đại, nhiều ánh sáng tự nhiên. An ninh 24/7.",
        "address": "Đường số 10, Tân Quy",
        "district": "Quận 7",
        "city": "Hồ Chí Minh",
        "latitude": 10.7412,
        "longitude": 106.7025,
        "room_type": "apartment",
        "area_m2": 35,
        "price_rent": 8500000,
        "price_electricity": 3500,
        "price_water": 100000,
        "status": "active",
        "is_shared_owner": False,
        "max_occupants": 2,
        "avg_rating": 4.7,
        "review_count": 3,
        "tags": [
            {"id": "t1", "name": "Gác lửng", "slug": "gac-lung"},
            {"id": "t2", "name": "Nội thất", "slug": "noi-that"},
            {"id": "t3", "name": "An ninh", "slug": "an-ninh"},
        ],
        "facilities": [
            {"id": "f1", "listing_id": "1", "facility_type": "furniture", "name": "Giường nệm", "is_included": True},
            {"id": "f2", "listing_id": "1", "facility_type": "appliance", "name": "Máy lạnh", "is_included": True},
            {"id": "f3", "listing_id": "1", "facility_type": "building", "name": "Thang máy", "is_included": True},
        ],
        "images": [],
        "reviews": [
            {"id": "r1", "listing_id": "1", "user_id": "u1", "user_name": "Nguyễn Minh Anh", "rating": 5,
             "comment": "Phòng rất sạch sẽ, chủ nhà dễ thương."},
            {"id": "r2", "listing_id": "1", "user_id": "u2", "user_name": "Trần Đức Huy", "rating": 4,
             "comment": "Vị trí thuận tiện, gần siêu thị và trường học."},
        ],
    },
    {
        "id": "2",
        "landlord_id": "ll_2",
        "title": "Zen Corner Studio",
        "description": "Studio yên tĩnh, có cửa sổ lớn đón nắng. Phù hợp cho 1-2 sinh viên.",
        "address": "Lê Văn Lương",
        "district": "Quận 7",
        "city": "Hồ Chí Minh",
        "latitude": 10.7300,
        "longitude": 106.7050,
        "room_type": "studio",
        "area_m2": 25,
        "price_rent": 6200000,
        "price_electricity": 3500,
        "price_water": 100000,
        "status": "active",
        "is_shared_owner": False,
        "max_occupants": 2,
        "avg_rating": 3.5,
        "review_count": 2,
        "tags": [
            {"id": "t4", "name": "Cửa sổ lớn", "slug": "cua-so-lon"},
            {"id": "t5", "name": "Máy lạnh", "slug": "may-lanh"},
        ],
        "facilities": [
            {"id": "f4", "listing_id": "2", "facility_type": "appliance", "name": "Máy lạnh", "is_included": True},
        ],
        "images": [],
        "reviews": [],
    },
    {
        "id": "3",
        "landlord_id": "ll_1",
        "title": "Green Terrace Unit",
        "description": "Căn hộ có ban công rộng rãi nhiều cây xanh. Phù hợp cho nhóm bạn ở chung.",
        "address": "Khu Him Lam",
        "district": "Quận 7",
        "city": "Hồ Chí Minh",
        "latitude": 10.7450,
        "longitude": 106.6950,
        "room_type": "apartment",
        "area_m2": 50,
        "price_rent": 12000000,
        "price_electricity": 3800,
        "price_water": 20000,
        "status": "active",
        "is_shared_owner": False,
        "max_occupants": 4,
        "avg_rating": 4.7,
        "review_count": 3,
        "tags": [
            {"id": "t6", "name": "Ban công", "slug": "ban-cong"},
            {"id": "t7", "name": "Pet friendly", "slug": "pet-friendly"},
        ],
        "facilities": [],
        "images": [],
        "reviews": [],
    },
    {
        "id": "4",
        "landlord_id": "ll_3",
        "title": "Phòng trọ sinh viên Bách Khoa",
        "description": "Phòng trọ giá rẻ gần ĐH Bách Khoa cơ sở 1. Có máy lạnh, wifi miễn phí, không chung chủ.",
        "address": "268 Lý Thường Kiệt, Phường 14",
        "district": "Quận 10",
        "city": "Hồ Chí Minh",
        "latitude": 10.7724,
        "longitude": 106.6600,
        "room_type": "single",
        "area_m2": 20,
        "price_rent": 2800000,
        "price_electricity": 3500,
        "price_water": 80000,
        "status": "active",
        "is_shared_owner": False,
        "max_occupants": 2,
        "avg_rating": 4.2,
        "review_count": 5,
        "tags": [
            {"id": "t8", "name": "Máy lạnh", "slug": "may-lanh"},
            {"id": "t9", "name": "Wifi", "slug": "wifi"},
            {"id": "t10", "name": "Gần trường", "slug": "gan-truong"},
        ],
        "facilities": [
            {"id": "f5", "listing_id": "4", "facility_type": "appliance", "name": "Máy lạnh", "is_included": True},
            {"id": "f6", "listing_id": "4", "facility_type": "amenity", "name": "Wifi miễn phí", "is_included": True},
        ],
        "images": [],
        "reviews": [
            {"id": "r6", "listing_id": "4", "user_id": "u6", "user_name": "Trần Văn Nam", "rating": 4,
             "comment": "Phòng ổn, gần trường đi bộ 5 phút. Chủ không ở cùng nên khá thoải mái."},
            {"id": "r7", "listing_id": "4", "user_id": "u7", "user_name": "Lê Hoàng Phúc", "rating": 5,
             "comment": "Giá rẻ, có máy lạnh, wifi mạnh. Phù hợp sinh viên Bách Khoa."},
        ],
    },
    {
        "id": "5",
        "landlord_id": "ll_4",
        "title": "Phòng trọ gần ĐH Sư Phạm",
        "description": "Phòng trọ sạch sẽ, an ninh tốt, gần ĐH Sư Phạm TP.HCM. Có gác lửng.",
        "address": "280 An Dương Vương, Phường 4",
        "district": "Quận 5",
        "city": "Hồ Chí Minh",
        "latitude": 10.7590,
        "longitude": 106.6800,
        "room_type": "single",
        "area_m2": 18,
        "price_rent": 2500000,
        "price_electricity": 3500,
        "price_water": 80000,
        "status": "active",
        "is_shared_owner": True,
        "max_occupants": 1,
        "avg_rating": 3.8,
        "review_count": 2,
        "tags": [
            {"id": "t11", "name": "Gác lửng", "slug": "gac-lung"},
            {"id": "t12", "name": "An ninh", "slug": "an-ninh"},
        ],
        "facilities": [],
        "images": [],
        "reviews": [],
    },
    {
        "id": "6",
        "landlord_id": "ll_5",
        "title": "Studio cao cấp Thủ Đức",
        "description": "Studio full nội thất, view sông thoáng mát. Gần KCN và các trường ĐH khu Thủ Đức.",
        "address": "Võ Văn Ngân, Phường Linh Chiểu",
        "district": "Thủ Đức",
        "city": "Hồ Chí Minh",
        "latitude": 10.8500,
        "longitude": 106.7580,
        "room_type": "studio",
        "area_m2": 30,
        "price_rent": 4500000,
        "price_electricity": 3500,
        "price_water": 100000,
        "status": "active",
        "is_shared_owner": False,
        "max_occupants": 2,
        "avg_rating": 4.5,
        "review_count": 4,
        "tags": [
            {"id": "t13", "name": "Nội thất", "slug": "noi-that"},
            {"id": "t14", "name": "Máy lạnh", "slug": "may-lanh"},
            {"id": "t15", "name": "Wifi", "slug": "wifi"},
        ],
        "facilities": [
            {"id": "f7", "listing_id": "6", "facility_type": "appliance", "name": "Máy lạnh", "is_included": True},
            {"id": "f8", "listing_id": "6", "facility_type": "furniture", "name": "Giường, tủ, bàn", "is_included": True},
            {"id": "f9", "listing_id": "6", "facility_type": "amenity", "name": "Wifi miễn phí", "is_included": True},
        ],
        "images": [],
        "reviews": [
            {"id": "r8", "listing_id": "6", "user_id": "u8", "user_name": "Nguyễn Thảo My", "rating": 5,
             "comment": "Phòng đẹp, nội thất mới. Khu vực an ninh, gần trạm xe buýt."},
        ],
    },
]

# ── Mock Roommate Profiles (mirrors frontend mockData/matchingProfiles.ts) ──

MOCK_PROFILES: list[dict] = [
    {
        "id": "1", "user_id": "101",
        "full_name": "Minh Khang", "age": 21,
        "avatar": "",
        "gender": "male",
        "university": "Đại học Kinh tế TP.HCM",
        "budget_min": 2500000, "budget_max": 4000000,
        "preferred_districts": ["Quận 1", "Quận 3", "Bình Thạnh"],
        "sleep_time": "normal", "wake_time": "early",
        "cleanliness": 4,
        "is_smoker": False, "drinks_alcohol": False,
        "has_pets": True, "is_introvert": True,
        "ok_with_smoker": False, "ok_with_pets": True,
        "bio": "Sinh viên năm 3 ngành Kinh tế, thích đọc sách và nuôi mèo.",
        "is_verified": True, "is_active": True,
        "location": "Quận 1, TP.HCM",
    },
    {
        "id": "2", "user_id": "102",
        "full_name": "Anh Tuấn", "age": 22,
        "avatar": "",
        "gender": "male",
        "university": "Đại học Bách Khoa TP.HCM",
        "budget_min": 3000000, "budget_max": 5000000,
        "preferred_districts": ["Quận 10", "Gò Vấp"],
        "sleep_time": "late", "wake_time": "normal",
        "cleanliness": 5,
        "is_smoker": False, "drinks_alcohol": True,
        "has_pets": False, "is_introvert": False,
        "ok_with_smoker": False, "ok_with_pets": True,
        "bio": "Gamer và coder. Tìm bạn cùng phòng chill.",
        "is_verified": True, "is_active": True,
        "location": "Quận 10, TP.HCM",
    },
    {
        "id": "3", "user_id": "103",
        "full_name": "Thu Hà", "age": 20,
        "avatar": "",
        "gender": "female",
        "university": "Đại học Ngoại Thương",
        "budget_min": 2000000, "budget_max": 3500000,
        "preferred_districts": ["Quận 3", "Quận 7"],
        "sleep_time": "early", "wake_time": "early",
        "cleanliness": 5,
        "is_smoker": False, "drinks_alcohol": False,
        "has_pets": False, "is_introvert": True,
        "ok_with_smoker": False, "ok_with_pets": False,
        "bio": "Sinh viên năm 2, thích nấu ăn tại nhà.",
        "is_verified": True, "is_active": True,
        "location": "Quận 3, TP.HCM",
    },
    {
        "id": "4", "user_id": "104",
        "full_name": "Đức Minh", "age": 23,
        "avatar": "",
        "gender": "male",
        "university": "Đại học Sư Phạm TP.HCM",
        "budget_min": 1800000, "budget_max": 3000000,
        "preferred_districts": ["Thủ Đức", "Quận 9"],
        "sleep_time": "normal", "wake_time": "early",
        "cleanliness": 3,
        "is_smoker": True, "drinks_alcohol": True,
        "has_pets": False, "is_introvert": False,
        "ok_with_smoker": True, "ok_with_pets": True,
        "bio": "Sinh viên năm cuối, đang thực tập.",
        "is_verified": False, "is_active": True,
        "location": "Thủ Đức, TP.HCM",
    },
    {
        "id": "5", "user_id": "105",
        "full_name": "Ngọc Trâm", "age": 21,
        "avatar": "",
        "gender": "female",
        "university": "Đại học RMIT",
        "budget_min": 5000000, "budget_max": 8000000,
        "preferred_districts": ["Quận 7", "Quận 2"],
        "sleep_time": "late", "wake_time": "late",
        "cleanliness": 4,
        "is_smoker": False, "drinks_alcohol": True,
        "has_pets": True, "is_introvert": False,
        "ok_with_smoker": False, "ok_with_pets": True,
        "bio": "Fashionista, lover of cats and coffee.",
        "is_verified": True, "is_active": True,
        "location": "Quận 7, TP.HCM",
    },
    {
        "id": "6", "user_id": "106",
        "full_name": "Hoàng Long", "age": 24,
        "avatar": "",
        "gender": "male",
        "university": "Đại học Khoa Học Tự Nhiên",
        "budget_min": 2000000, "budget_max": 3500000,
        "preferred_districts": ["Quận 5", "Quận 10"],
        "sleep_time": "very_late", "wake_time": "late",
        "cleanliness": 3,
        "is_smoker": False, "drinks_alcohol": False,
        "has_pets": False, "is_introvert": True,
        "ok_with_smoker": True, "ok_with_pets": False,
        "bio": "Nghiên cứu sinh ngành Vật lý, hay ngủ muộn vì lab.",
        "is_verified": True, "is_active": True,
        "location": "Quận 5, TP.HCM",
    },
    {
        "id": "7", "user_id": "107",
        "full_name": "Mai Linh", "age": 19,
        "avatar": "",
        "gender": "female",
        "university": "Đại học Kinh tế TP.HCM",
        "budget_min": 2500000, "budget_max": 4000000,
        "preferred_districts": ["Bình Thạnh", "Quận 1"],
        "sleep_time": "early", "wake_time": "early",
        "cleanliness": 5,
        "is_smoker": False, "drinks_alcohol": False,
        "has_pets": False, "is_introvert": False,
        "ok_with_smoker": False, "ok_with_pets": True,
        "bio": "Năm nhất UEH, thích chạy bộ buổi sáng.",
        "is_verified": False, "is_active": True,
        "location": "Bình Thạnh, TP.HCM",
    },
    {
        "id": "8", "user_id": "108",
        "full_name": "Quốc Bảo", "age": 22,
        "avatar": "",
        "gender": "male",
        "university": "Đại học FPT",
        "budget_min": 3000000, "budget_max": 5500000,
        "preferred_districts": ["Quận 9", "Thủ Đức"],
        "sleep_time": "late", "wake_time": "normal",
        "cleanliness": 4,
        "is_smoker": False, "drinks_alcohol": True,
        "has_pets": True, "is_introvert": False,
        "ok_with_smoker": False, "ok_with_pets": True,
        "bio": "Sinh viên IT yêu thú cưng. Có 1 chú golden nhỏ.",
        "is_verified": True, "is_active": True,
        "location": "Quận 9, TP.HCM",
    },
]

# ── Mock Reviews (for get_reviews tool) ──────────────────────────────

MOCK_REVIEWS: dict[str, list[dict]] = {
    "1": [
        {"id": "r1", "listing_id": "1", "user_id": "u1", "user_name": "Nguyễn Minh Anh",
         "rating": 5, "comment": "Phòng rất sạch sẽ, chủ nhà dễ thương. View đẹp ban đêm."},
        {"id": "r2", "listing_id": "1", "user_id": "u2", "user_name": "Trần Đức Huy",
         "rating": 4, "comment": "Vị trí thuận tiện, gần siêu thị. Hơi ồn cuối tuần."},
        {"id": "r3", "listing_id": "1", "user_id": "u3", "user_name": "Lê Thị Hồng",
         "rating": 5, "comment": "An ninh tốt, bảo vệ 24/7. Máy lạnh mới."},
    ],
    "2": [
        {"id": "r4", "listing_id": "2", "user_id": "u4", "user_name": "Phạm Quốc Bảo",
         "rating": 4, "comment": "Studio nhỏ gọn đủ cho 1 người. Cửa sổ lớn rất thoáng."},
        {"id": "r5", "listing_id": "2", "user_id": "u5", "user_name": "Võ Thanh Mai",
         "rating": 3, "comment": "Phòng ổn, hơi nóng buổi trưa vì hướng Tây."},
    ],
    "4": [
        {"id": "r6", "listing_id": "4", "user_id": "u6", "user_name": "Trần Văn Nam",
         "rating": 4, "comment": "Gần trường đi bộ 5 phút. Chủ không ở cùng."},
        {"id": "r7", "listing_id": "4", "user_id": "u7", "user_name": "Lê Hoàng Phúc",
         "rating": 5, "comment": "Giá rẻ, có máy lạnh, wifi mạnh. Phù hợp sinh viên."},
    ],
    "6": [
        {"id": "r8", "listing_id": "6", "user_id": "u8", "user_name": "Nguyễn Thảo My",
         "rating": 5, "comment": "Phòng đẹp, nội thất mới. Khu vực an ninh."},
    ],
}

# ── University → approximate location mapping ───────────────────────

UNIVERSITY_LOCATIONS: dict[str, dict] = {
    "Đại học Bách Khoa TP.HCM": {"lat": 10.7724, "lng": 106.6600, "districts": ["Quận 10", "Quận 3"]},
    "Bách Khoa": {"lat": 10.7724, "lng": 106.6600, "districts": ["Quận 10", "Quận 3"]},
    "Đại học Kinh tế TP.HCM": {"lat": 10.7836, "lng": 106.6999, "districts": ["Quận 3", "Quận 1"]},
    "UEH": {"lat": 10.7836, "lng": 106.6999, "districts": ["Quận 3", "Quận 1"]},
    "Đại học Sư Phạm TP.HCM": {"lat": 10.7627, "lng": 106.6821, "districts": ["Quận 5", "Quận 10"]},
    "Đại học RMIT": {"lat": 10.7297, "lng": 106.6952, "districts": ["Quận 7"]},
    "Đại học Ngoại Thương": {"lat": 10.7850, "lng": 106.6950, "districts": ["Quận 3", "Quận 1"]},
    "Đại học FPT": {"lat": 10.8414, "lng": 106.8098, "districts": ["Quận 9", "Thủ Đức"]},
    "Đại học Khoa Học Tự Nhiên": {"lat": 10.7628, "lng": 106.6822, "districts": ["Quận 5", "Quận 10"]},
}
