apiVersion: v1
kind: ConfigMap
metadata:
  name: core-config
  namespace: totoro
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://core-db:5432/core_db"
  DB_USERNAME: "postgres"
  DB_PASSWORD: "postgres"
  IDENTITY_SERVICE_URL: "http://identity-service:8081"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
